### ISSUE TITLE
Use pipe as entry file alternative

### ISSUE THREAD

**Issue by MartinHelmut** [KnisterPeter/paeckchen#178]
A nice little feature would be to use the pipe operator instead of the `--entry` file parameter, e.g.:

``` shell
cat file.js | paeckchen-cli > output.js
```

**Comment by KnisterPeter** [comment]
What do you have in mind for multiple input files. This is primarily a bundler (aka many to one transformation). I think we could not separate multiple input files if they are just given by stdin to a process.

**Comment by MartinHelmut** [comment]
@KnisterPeter You're right, this is not useful for multiple entry files, but for one "main" application entry file resolving all necessary imported modules. I will try to add some further informations the next few days.
