### ISSUE TITLE
incremental rebuilds issues

### ISSUE THREAD

**Issue by ghost** [KnisterPeter/paeckchen#179]
I faced issues regarding this when I was trying it out. For me on a windows computer thing didn't instantly update. Say I did a change in A.js and output should be in b.js. The changes was not visible.

Also when I wrote a new module and imported it in A.js , it was not visible in b.js.

For things to work I had to restart the watch task. And there was no validations. So everything was 

allowed. Even `export default export const a ) let`

I did a comparison now with a similar watch solution I fixed locale without chokidar, and I still face this issues with the paeckchen watch task. .

**Comment by ghost** [comment]
Plans to add time to your watch task, so it will be like this:

``` js
re-bundled (17ms). Now... - watching for changes...
```

**Comment by KnisterPeter** [comment]
Sounds like a chokidar bug. I'll try to check this.
I think on windows OS there is no native support for hooking watchers into the filesystem so it does polling. That could be a lot slower than expected.

> Now... - watching for changes...

Good idea

**Comment by KnisterPeter** [comment]
Can you give some more detail about your setup.
I've retested with Win7 and nodejs 6 in a virtual machine.
- Checkout paeckchen master branch
- run `npm run bootstrap`
- run `npm run test`
- go into examples/es2015-modules
- run `npm install`
- run `npm start -- --watch` (node the double -- !)

Then change for example the `main.js` in the example project.
For me this did instant rebuilds.

**Comment by ghost** [comment]
Hey. Sorry late reply, but I'm stuck in Japan atm. I can check more regarding this soon as I'm back home.
I was using Windows 10 latest build. NodeJS 6.

**Comment by KnisterPeter** [comment]
I've discovered a bug about the watching of updated files. The #191 fixes this.

**Comment by KnisterPeter** [comment]
Closing this for now. Feel free to reopen if the problem still occurs.
