### ISSUE TITLE
The file `paeckchen.cache.json` is created, even though debug is set to false.

### ISSUE THREAD

**Issue by clebert** [KnisterPeter/paeckchen#267]
**Version:** paeckchen-cli@0.4.0

**paeckchen.json:**

``` json
{
  "input": {
    "source": "es5"
  },
  "output": {
    "folder": "public/js",
    "file": "app.js",
    "runtime": "browser",
    "sourceMap": true
  },
  "debug": false
}
```

**Command:** `./node_modules/.bin/paeckchen --entry dist/index.js`

**Result:** The file `paeckchen.cache.json` is created, even though debug is set to false.

**Example setup:** https://github.com/clebert/ts-paeckchen-setup

**Comment by KnisterPeter** [comment]
@clebert: Still valid or could this be closed?
