### ISSUE TITLE
Parallel bundling

### ISSUE THREAD

**Issue by KnisterPeter** [KnisterPeter/paeckchen#28]
paeckchen should support bundling of modules in parallel (e.g. spawn multiple processes for module processing)
### Implementation scheme

The main process should at start time spawn that many worker threads as cpu cores are available.  
There need to be some communication channel between workers and main thread - I would favor some kind of message-passing (e.g. node IPC). As there are a few messages which need to be transered.
Creating an own protocol based on stdin/stdout could be tedious and slow.

Whenever there is a module scheduled for bundling the main thread delegates that work to a free worker (message). Which then starts parsing the source and checking for dependencies. Every found dependency is then scheduled at the main thread (message). When the worker is done with rewriting the AST the result is transfered back to the master (message). The master finally integrates the prepared module AST into the bundle.

**Comment by KnisterPeter** [comment]
@ZauberNerd: How was the npm module called you mentioned for parallelism?

**Comment by ZauberNerd** [comment]
I haven't used it myself, but I've seen a couple tools that are using this:
https://www.npmjs.com/package/node-worker-pool

**Comment by KnisterPeter** [comment]
I found that myself, but it does not create an IPC channel between master and clients.
We need a lot of message passing. That will slow down using only stdio I think.

**Comment by marionebl** [comment]
Perhaps https://www.npmjs.com/package/webworker-threads would fit the bill? Nice things about it:
-  (Web)Worker API 🌍 
-  IPC via websockets via sockets 🚀

**Comment by ZauberNerd** [comment]
That looks good.
Also interesting: https://github.com/nodejs/node/pull/2133 ;)

**Comment by ZauberNerd** [comment]
Spiked with @marionebl in https://github.com/KnisterPeter/paeckchen/tree/workers

**Comment by ZauberNerd** [comment]
webworker-threads can't be used, because it cannot `require()` modules and it needs native node modules (`fs`, etc).
We have written our own worker pool with `child_process.fork`.
Preliminary tests are showing no speed improvement - possibly a test or implementation error. Needs further investigation.

**Comment by KnisterPeter** [comment]
Defered until #147 is solved
