### ISSUE TITLE
Code generation

### ISSUE THREAD

**Issue by KnisterPeter** [KnisterPeter/paeckchen#30]
The current code generation process is not optimal.
We add comments for debugging hints - unfortunately in some cases this results in invalid code (e.g. webpack prebundled modules with comments)

Write our own codegen?

**Comment by ZauberNerd** [comment]
Can we fix that upstream?

**Comment by KnisterPeter** [comment]
I have not looked into it right now. I think its may be a bit complicated and too opinionated what we need.

**Comment by KnisterPeter** [comment]
I think with full source-map support this could be closed and all hacks to get around comment injection could be removed.
