### ISSUE TITLE
add support for uglify dead-code elimination

### ISSUE THREAD

**Issue by KnisterPeter** [KnisterPeter/paeckchen#53]
There should be a plugin to replace AST parts which could be identified as dead-code.
E.g. process.env.NODE_ENV

**Comment by ZauberNerd** [comment]
Not sure if that should be part of the bundler.
IMO it should be done before or after bundling (Babel or post-processing / uglyfying).
Otherwise you'll either end up with an unclear separation of what the bundler should or should not do or you'll introduce user defined plugins and end up in the same space as browserify / webpack ;)

**Comment by KnisterPeter** [comment]
The main idea is that a plugin will rewrite define AST parts (e.g. process.env.NODE_ENV) and replaces it with the defined value. There should be no uglifyjs plugin or anything like this.

The goal of the rewritten AST is to transform this:

``` js
if (process.env.NODE_ENV !==  'production') {
  // something here
}
```

into: 

``` js
if ('production' !==  'production') {
  // something here
}
```

The resulting bundle will the be piped into uglifyjs which removes this code parts because it knows its dead-code.

**Comment by KnisterPeter** [comment]
But maybe you are right and it could be done afterwards. Beforehand is not really possible, because you can not control your thirdparty dependencies.

**Comment by marionebl** [comment]
My two cents: I'm with @ZauberNerd on this - don't concern paeckchen with plugins or magic browserify-plugin super powers. That being said we need to guide users on topics we exclude from the problem space compared to browserify and webpack's bundler related functionality. A paeckchen-handbook could contain this kind of stuff.

**Comment by KnisterPeter** [comment]
Currently I'm with you on this topic.
But I guess it could be very expensive in a build chain to have all this done again with another tool parsing and regenerating the whole source.

But currently this is fair enough.
