### ISSUE TITLE
Idea: Increase performance by not doing unneccessary AST visits

### ISSUE THREAD

**Issue by ZauberNerd** [KnisterPeter/paeckchen#59]
This would need some performance testing / spike first, but we could investigate if it would be benefical to scan the source code for potentially interesting patterns before the run the AST visitor on them.
Similar to what Ben Newman is doing here: https://github.com/benjamn/module-imports/blob/92f3f0cabb50f9e3a3c0e7258f5ab4f373ae7b42/index.js#L8-L18

**Comment by ZauberNerd** [comment]
It could potentially be a part of the plugins (similar to `shouldComponentUpdate`)

**Comment by KnisterPeter** [comment]
I agree with you and had a short discussion with @marionebl about creating a minimal parser which only understands es6 modules and maybe the require-function.
That way everything else could be just skipped.

Shouldn't be too hard to create such a beast. And it would improve the AST walking very much.

**Comment by KnisterPeter** [comment]
The aproach of Ben Newman currently does not match the designed API of paeckchen, because there is no knowledge of the source-code but only the AST is transfered between internal modules.
