### ISSUE TITLE
setup multi-package repository

### ISSUE THREAD

**Issue by KnisterPeter** [KnisterPeter/paeckchen#60]
We will need at least a few packages for npm (e.g. cli, gulp plugin, grunt-plugin, ...).
As it would be easier to have everything related to paeckchen in one git repo we should setup something like lerna.

**Comment by marionebl** [comment]
I'm pulling this and give it a shot!

**Comment by KnisterPeter** [comment]
Currently lerna isn't really feasable for paeckchen.
- When running `lerna boostrap` (the `npm install` of lerna) then it does not execute the `preinstall` and `postinstall` hooks.
- It does a lot in parallel and has some problems with stdout/stderr (swallowing errors or logs)

With the only benefit of simplifiing publishing I think it introduces too much development pain.
