### ISSUE TITLE
implement caching for fast restart-performance

### ISSUE THREAD

**Issue by KnisterPeter** [KnisterPeter/paeckchen#67]
There should be a state cache which enables paeckchen to have a really quick restart time.

Thinks we need to persist for this are:
- [x] paeckchen (result) AST
- [x] globals state
- [x] wrapped modules state
- [x] ~~bundled modules state (not sure on this one, the wrapped modules state should be sufficient)~~
- [x] ~~the bundle queue~~

ToDOs:
- [x] implement basic caching
- [x] add development switch (production builds should not rely on caching)
- [x] implement cache invalidation
- [x] add debug switch to cli

**Comment by marionebl** [comment]
First thing to decide: Persist directly onto disc or in an abstraction layer (say leveldb)? Second thing: Where to persist? In $CWD, $TMP or even $USR/paeckchen?

**Comment by KnisterPeter** [comment]
I think the project folder ($CWD) would be the best place (but in a dot-folder below it).
$TMP may seem a natural target but most OSes will whipe $TMP on reboot. Then you loose all your caching and have a slow restart.
What do you mean with $USR/paeckchen?
