### ISSUE TITLE
output generation

### ISSUE THREAD

**Issue by KnisterPeter** [KnisterPeter/paeckchen#70]
paeckchen should optinally write the result to the fs with a given name and folder.
Currently the result is only wirtten to stdout.

**Comment by marionebl** [comment]
Should this be part of the cli? I think paeckchen (the library) should cause aus little io as possible and leave the reading of entries and writing of results to implementers (eg paeckchen cli)

**Comment by KnisterPeter** [comment]
I think that's not a good idea, because it has dependencies to the watch mode.
And the watch handling should not belong into the cli bundle.

**Comment by marionebl** [comment]
What kind of dependency is this? Couldn't paeckchen signal rebuilds to implementers?

**Comment by KnisterPeter** [comment]
It is okay to signal for rebuild, but IMHO that not cli concern.
It would be nice to let the cli define for example a trigger-file which will signal a rebuilding.
