### ISSUE TITLE
create logger abstraction

### ISSUE THREAD

**Issue by KnisterPeter** [KnisterPeter/paeckchen#88]
It should be possible to do some debug logging, set verbosity level or maybe tracing performance.

**Comment by marionebl** [comment]
I'd vote for util.debuglog here.

**Comment by KnisterPeter** [comment]
Thought about it too. I'll have to investigate if the loglevels are sufficient.

**Comment by marionebl** [comment]
`util.debuglog` has no log levels but rather allows for indefinitely deep enabling of debug logs. Say in some sort of task runner project paeckchen is used an should be debugged.

``` shell
# Enables **all** debuglog statements
NODE_DEBUG=paeckchen gulp paeckchen
```

I'd argue this is more powerful and a better fit for library debugging than an elaborate log level system. If need be we could prefix log messages with levels and then a simple 

``` shell
NODE_DEBUG=paeckchen gulp paeckchen | grep "loglevel"
```

fits the exact same bill without all the log system cruft.
